apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws_credentials
  namespace: demo
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAsmISlskM7JcR1VepPhFnBfsJvpuDCjZOZyGNkIJIWbS0TSkT5+g/Sv3tGuRUtfa60XAE91OX2HX0mTWAxZKTNdoSTfCJfqWHoj7c6hfbtz1AKvxLQal4hjPuOGtUsJD7D/8/fa51U2QDxpHJAnUHuky3fvGzAjOdI6Nni8bxZ0GNEKRAmqVQC0wLk9nH3+CjEi3iCPHta698WHR16G21GFr/E4ilweRza14xwzo09TzyUR4K64c3SYMXzH+MVx+Nb92ZwooLouLttCwfHTVz6wyNLms0sb+1vasb/CUt3JC9T9On8UBqHPOg5E1zREDDoPjZtsbzXBcpnHUj5W7IohcJGTVX1Xkp1F3dTutFYw0a73/iS5/77Wp26LNhk7UnocDCD8b8K08UKF57wRb91dnRXEtgdDuo6mLewPb90gRcwdfhGCt1qO27Sst5LapLc5fws24JlydPJEe5J51d0xSEUGhKvl35KUySgjBJJJ/szOeITaJXsLBcUCwHLe8Qp5mblV5zlB6PuM2tb82TVY+VVDeM13WvFIv2Ma7iRRnQY/FqB9wLyUaOw9HNaHxqKrYQCFPKr80J8DnmJ042KoCCJ8XORLlJFQvNBvcDH7FtYRwDSS/2PeOh9y8TvbI5ZAnaFTYGiBYllKOzUq5BuCP9jjji/N15Y6NwDz/v6xBxRJUuqJKdLj6xeFrMB+irvZnCywLs/Qiy7AIh0yS7Jv56grA==
    AWS_SECRET_KEY: AgAtF/JOpnavkqcRZgSFNVimp4OjiODANPMoXQcnf6ICVn4Bt/zfy+cOd+X16VPSRMsW8k7zH6imBrOA3kVZw54bns5mFWnAXx1kl5W9MipLtl/HBIvQp8JxfvHaVe8LeFPoN9DR/2418QDYpmvzpAZ3DJXSuIpVjbm2Q8LeoKAZxA8tomudmPEwu4ibBfg8p9pdWgTYNbloMxscbs6xMud3XIseAug+ZSf6SvTbg5L0H9wDvwPof9nd+5TuTJj6+x4Mxjs1ys/N8CL8gy6qk4u0XOevOGai80SUu+sOBztniNSUhRosT7PYFC2aNks6AgPdt4QIYtv6GGwv5ZAPiSyPwpYsz71K+Lo+en2uGnblmt4LQiUuBA014VxJkMJ+uaSOmOCKfDVoGpZzjzPfTQliQwHKfzvoMvpC1wJi7orPU4WLrlvAQgZ1JrbalmC11YcwMSqYoNMdcUIfccAWsDNH21EOnwEzasFgfoTm7RkeJSGqjWiIjvb4FjpqQdOh+Uun0NVkBZt5C5nvkz8PZ1AwdqSvq1fqCqn8B4wy2XItsbVJ9cFOqCsbo+kYK1uv9EM/h1TbIusiBmy0GyjmkKf00Dn/QOztRj5tk6YFd/8exLp/Zg2reIfffifGxfLBW34ZO0qPsYoVRYo5OC6mcZbxAbsdbiLQgEqgQxJjHJ+g7tpYOnVXCMstjBbF1Y7TV8fA5wYuQnHq1WMfFA6pONJqI0iFI6rt77ZW7AaZmHHywhpF4kgiSn90
  template:
    metadata:
      creationTimestamp: null
      name: aws_credentials
      namespace: demo

