apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgAHgUrLqXMANIiViBUO06ZH7VkN/8cA6rd1a3I4M4pW6p5QbajpMrIk+3jnDO6a58+2YvoXzVCvbB93tAcaWUvx9FupafONGWmFoqBKmjrakhmZZ7rz2YPxDZkXjTzHUgVEr52f4mIVTGEUQsKf43rFuKxq7h+UXocH8dK/TVyvWIUiBYS+a3gfKNNvxG4jH16nzbhrTvhkwEXECrDSvh1MjZ2+b5fxjk0rVyzb1nop1Zm8jJ7mEKZHyJUznzq+znePgGPmGeZYvUFlBVkEixfNlUMwuLKbBhayK3xPIzTzbAvVsCi4dx7yp+mUOMXv/jv6xPe8K/6A2PJmhx/aqOQrEMmJC8yQIKoa/6q0Xd8TmIiEd49QUgVffLQVUjoVbSV1SOsc9QYq5FsEPreDdxBsSVEB7Mye6nGfpgWBRTUwPXdVtDMQc/cgUvAMsHPttlTYUKEMMID9oi/UAuc05uVlsmntyUPvXZWECWxCCLVARKrQZzO2FTCbYRVEK2qRpDzgHyWV/P2czHNNWOhIckPu0cgFKXnVVNkovZxBZiXiHKflGLBan4W3FkcU3j6W5L20cSYdOaWLtp22GYY4qwSJ5ujO3vT6FAoAiq5aSRITmbDrNc7AR0wWIZPRHyYHTGN6iJQa9x0+8lMK7t+v8mJKCTLDMSn0HrC15g0QuDnJGt0WrVDi3xxDBtNCl2bsSZdCUP7qFtVE4hMY7UVPAvI=
    username: AgAVbE2pR7Lo2kcHqL5Rr33Rw1s0lQeIlJeYJU+cIAllgl05L9flSLvkNIJufvLRJv0WcT78pjkiTE8gCHUzJAPFAHhH4cYHmjFbfsez6gt0R1C8kQubyWZcszGdCTzYLiquhQjA9Fao0Kz7HC5skWkK+FHoWTy/E8y7Dj8tg6THNNtN4WmGAU7iHZpmSK/6BRlPVMph3bmIvQFL3sR6BXWy9IX7FsMtpTVDa7DwHuD2hbP/oryu1alDDtplE/fgIwDcHY1DUvdvwPp6J9NIqTjPdk2PcUD7wvm5/HEqQr3NFrgqgnKmWFM+s9Jh5JS5eSOdqi7dU/GuLS0XpVDx3rlYsMP+E/zI1fQqCdM5wUf7/tfzG4bz91uinihiqKRTIYu+vuLriwGzOgv349ey1NE/+zqop7/Caccbh3+J7WlD4h6UO40FfIlXCEW5QB6IkE7ExkQD41ouJJQYqCwy3RXuhNGkBRQfqRjIcpgjH1U4HYUGpQ2VGKK8/aCaP8H9htWGkXw9JuAAOFx2d6ESpssIMSj9k0R+BPzRu+7CeBHZOp64NsNdKo4mPO4bRtgq2cajGdREyVRto9qPGBPFCHPM+RVNcPypGi6EGUyGeh0wgvtPsInG2DhBAzcPbRGGhlAk0FZdVaIaAYLTVBwJ3kOzWjs7Or3pgd2ARinaH46DqtepjZdIun1Dihot/oolIWLhoy8wzKrDz5kZk/8=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

