apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver
    image: k8s.gcr.io/kube-apiserver-amd64:v1.22.0
    command:
    - kube-apiserver
    - --authorization-mode=RBAC
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --insecure-bind-address=0.0.0.0
    - --insecure-port=8080
    - --secure-port=8443
    - --service-cluster-ip-range=10.0.0.0/24
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    volumeMounts:
    - name: k8s-certs
      mountPath: /etc/kubernetes/pki
      readOnly: true
  volumes:
  - name: k8s-certs
    hostPath:
      path: /etc/kubernetes/pki
