# especifica qué permisos se otorgan al usuario oscarUser en el namespace espacio-secretos
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: espacio-secretos
  name: secret-reader
rules:
- apiGroup: rbac.authorization.k8s.io
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]