apiVersion: v1

kind: Pod

metadata:

  name: constraints-cpu-demo

spec:

  containers:

  - name: oscarnamespace

    image: nginx

    resources:

      limits:

        cpu: "800m"

      requests:

        cpu: "500m"
